# ---------------------------------------------------------------------------
# lambda.tf
# The single backend Lambda function, its log group, and a placeholder
# deployment package.
#
# The real function implementation is written and deployed later (out of band).
# Terraform ships an inert placeholder so the resource can be created cleanly;
# `lifecycle.ignore_changes` prevents Terraform from clobbering code that is
# subsequently deployed by a CI/CD pipeline or `aws lambda update-function-code`.
# ---------------------------------------------------------------------------

# --- Placeholder deployment package ----------------------------------------
# A minimal handler is generated at plan/apply time so no binary artifact needs
# to be committed to the repository. It simply returns HTTP 501 Not Implemented.
data "archive_file" "lambda_placeholder" {
  type        = "zip"
  output_path = "${path.module}/build/lambda_placeholder.zip"

  source {
    filename = "index.js"
    content  = <<-EOT
      // Placeholder handler generated by Terraform.
      // Replace by deploying the real implementation (see infra/README.md).
      exports.handler = async () => ({
        statusCode: 501,
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ message: "Not implemented. Deploy the real Lambda package." }),
      });
    EOT
  }
}

# --- CloudWatch log group ---------------------------------------------------
# Created explicitly (rather than implicitly by first invocation) so retention
# is enforced and the IAM policy can be scoped to a known ARN.
resource "aws_cloudwatch_log_group" "lambda" {
  name              = local.log_group_name
  retention_in_days = 14
}

# --- Lambda function --------------------------------------------------------
resource "aws_lambda_function" "api" {
  function_name = local.lambda_function_name
  description   = "Backend API for ${local.name_prefix}: /chat (Bedrock Nova Lite) and /admin/chats (DynamoDB)."
  role          = aws_iam_role.lambda.arn

  runtime = var.lambda_runtime
  handler = var.lambda_handler

  filename         = data.archive_file.lambda_placeholder.output_path
  source_code_hash = data.archive_file.lambda_placeholder.output_base64sha256

  memory_size = var.lambda_memory
  timeout     = var.lambda_timeout

  # Environment configuration the function implementation consumes.
  environment {
    # AWS_BEARER_TOKEN_BEDROCK is added only when a key is configured. When set,
    # the AWS SDK authenticates to Bedrock with this long-term API key (bearer
    # token) instead of SigV4-signing with the execution role. Omitting it while
    # empty lets the function fall back to the IAM role (iam.tf).
    variables = merge(
      {
        ENVIRONMENT         = var.environment
        DYNAMODB_TABLE_NAME = aws_dynamodb_table.chat_history.name
        # Runtime invoke id = inference profile (on-demand Nova Lite requires it).
        # IAM stays scoped to the underlying foundation model via bedrock_model_id.
        BEDROCK_MODEL_ID = var.bedrock_inference_profile_id
        ALLOWED_ORIGINS  = join(",", local.cors_allowed_origins)
        ADMIN_SECRET     = var.admin_secret
        # Active chat provider + Gemini config (Bedrock path kept intact).
        LLM_PROVIDER    = var.llm_provider
        GEMINI_MODEL_ID = var.gemini_model_id
      },
      var.bedrock_api_key != "" ? { AWS_BEARER_TOKEN_BEDROCK = var.bedrock_api_key } : {},
      var.gemini_api_key != "" ? { GEMINI_API_KEY = var.gemini_api_key } : {},
    )
  }

  # Ensure the log group (with retention) exists before the function.
  depends_on = [aws_cloudwatch_log_group.lambda]

  lifecycle {
    # The deployment package is managed out of band after the real code exists.
    # Ignore it here so `terraform apply` never reverts a deployed build.
    ignore_changes = [
      filename,
      source_code_hash,
    ]
  }
}
